[libraries.hvhdl_gigabit_ethernet]
files = [ 
"./mdio_driver/mdio_three_state_io_driver/mdio_three_state_io_driver_pkg.vhd",
"./mdio_driver/mdio_driver_pkg.vhd",
"./mdio_driver/mdio_driver_internal_pkg.vhd",
"./mdio_driver/mmd_access_functions_pkg.vhd",
"./mdio_driver/mdio_driver.vhd",

"./ethernet_rx_ddio/efinix_fpga_ddio_record.vhd",
"./ethernet_rx_ddio/ethernet_rx_ddio_pkg.vhd",
"./ethernet_rx_ddio/efinix_rx_ddio.vhd",
"./ethernet_clocks_pkg.vhd",
"./ethernet_common/PCK_CRC_32_D8.vhd",

"./ethernet_common/dual_port_ethernet_ram/ethernet_frame_ram_read_pkg.vhd",
"./ethernet_common/dual_port_ethernet_ram/ethernet_frame_ram_write_pkg.vhd",
"./ethernet_common/dual_port_ethernet_ram/dpram.vhd",

"./fifo/fifo_pkg.vhd",
"./fifo/fifo.vhd",

"./frame_transmitter/frame_transmitter_pkg.vhd",

"./ethernet_frame_receiver/ethernet_frame_receiver_pkg.vhd",

"./ethernet_tx/ethernet_tx_pkg.vhd",
"./ethernet_tx/ethernet_tx.vhd",

"./ethernet_rx/ethernet_rx_pkg.vhd",
"./ethernet_rx/ethernet_rx.vhd",

"./testbenches/transmit_test_pkg.vhd",]



